export const songConstants = {
  GET_SONG_REQUEST: "GET_SONG_REQUEST",
  GET_SONG_SUCCESS: "GET_SONG_SUCCESS",
  GET_SONG_FAILURE: "GET_SONG_FAILURE",

  SAVE_SONG_REQUEST: "SAVE_SONG_REQUEST",
  SAVE_SONG_SUCCESS: "SAVE_SONG_SUCCESS",
  SAVE_SONG_FAILURE: "SAVE_SONG_FAILURE",

  UPDATE_SONG_REQUEST: "UPDATE_SONG_REQUEST",
  UPDATE_SONG_SUCCESS: "UPDATE_SONG_SUCCESS",
  UPDATE_SONG_FAILURE: "UPDATE_SONG_FAILURE",

  DELETE_SONG_REQUEST: "DELETE_SONG_REQUEST",
  DELETE_SONG_SUCCESS: "DELETE_SONG_SUCCESS",
  DELETE_SONG_FAILURE: "DELETE_SONG_FAILURE",

  ADD_ROYALTY_REQUEST: "ADD_ROYALTY_REQUEST",
  ADD_ROYALTY_SUCCESS: "ADD_ROYALTY_SUCCESS",
  ADD_ROYALTY_FAILURE: "ADD_ROYALTY_FAILURE",

  UPDATE_ROYALTY_REQUEST: "UPDATE_ROYALTY_REQUEST",
  UPDATE_ROYALTY_SUCCESS: "UPDATE_ROYALTY_SUCCESS",
  UPDATE_ROYALTY_FAILURE: "UPDATE_ROYALTY_FAILURE",

  DELETE_ROYALTY_REQUEST: "DELETE_ROYALTY_REQUEST",
  DELETE_ROYALTY_SUCCESS: "DELETE_ROYALTY_SUCCESS",
  DELETE_ROYALTY_FAILURE: "DELETE_ROYALTY_FAILURE",
 

  CLEAR_TOAST : "CLEAR_TOAST",
};
