export const userConstants = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",

  SAVE_USER_ID: "SAVE_USER_ID",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  UPDATE_DP_REQUEST: "UPDATE_DP_REQUEST",
  UPDATE_DP_SUCCESS: "UPDATE_DP_SUCCESS",
  UPDATE_DP_FAILURE: "UPDATE_DP_FAILURE",

  GET_ARTIST: "GET_ARTIST",
  SAVE_ARTIST: "SAVE_ARTIST",
  DELETE_ARTIST: "DELETE_ARTIST",

  CLEAR_TOAST : "CLEAR_TOAST",
};
